# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20161013_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('calendar_month', models.DateField()),
                ('schedule_calendar', models.FileField(blank='True', default='', null='True', upload_to='schedule_calendar')),
            ],
        ),
    ]
