# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_schedulecalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecalendar',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('I', 'Irrelevent')], default='I', max_length=1),
        ),
    ]
