# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_schedulecalendar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Enter question here....')),
                ('answer', models.TextField(default='Enter answer here....')),
            ],
        ),
    ]
