# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmod',
            options={'verbose_name': 'FAQ'},
        ),
        migrations.AlterField(
            model_name='student',
            name='wavier_signed',
            field=models.BooleanField(default=False),
        ),
    ]
