# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20161103_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
