# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20161104_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_choices',
            field=models.CharField(choices=[('C', 'Child'), ('A', 'Adult')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
