# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event'},
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 13, 16, 41, 55, 256973, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
